version: '3.7'
services:
  Addition:
    image: additionservice
    build:
      context: .
      dockerfile: AdditionService/Dockerfile
    ports:
      - "8081:80"
      - "8082:443"
    networks:
      - local_network
    depends_on:
      - zipkin
      - seq
      
  Subtract:
    image: subtractionservice
    build:
      context: .
      dockerfile: SubtractionService/Dockerfile
    ports:
      - "8083:80"
      - "8084:443"
    networks:
      - local_network
    depends_on:
      - zipkin
      - seq
    
  Calculator:
    image: calculator
    build:
      context: .
      dockerfile: CalculationService/Dockerfile
    ports:
      - "8085:80"
      - "8086:443"
    networks:
      - local_network
    depends_on:
      - calculator-db
      - zipkin
      
  seq:
    image: datalust/seq:latest
    ports:
      - "5341:5341"
      - "5342:80"
    volumes:
      - seq_data:/data
    networks:
      - local_network
    environment:
      ACCEPT_EULA: "Y"

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_HOST=zipkin-storage
      - MYSQL_USER=zipkin
      - MYSQL_PASS=zipkin
    depends_on:
      - zipkin-storage
    networks:
      - local_network
      
  zipkin-storage:
      image: openzipkin/zipkin-mysql
      ports:
        - "3306:3306"
      volumes:
        - zipkin_data:/mysql/data
      networks:
        - local_network
  
  calculator-db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      MSSQL_SA_PASSWORD: "Password123"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql_data_db:/var/opt/mssql
    networks:
      - local_network
    
volumes:
  seq_data:
  zipkin_data:
  mssql_data_db:
networks:
  local_network:
    driver: bridge  
